package com.rpn.mosquetime.presentation.theme

import com.rpn.mosquetime.R
import com.rpn.mosquetime.utils.AppStringProvider

// Central string keys
class AppStrings(
    private val stringProvider: AppStringProvider
) {
    val app_name = stringProvider.getString(R.string.app_name)
    val settings = stringProvider.getString(R.string.settings)
    val theme = stringProvider.getString(R.string.theme)
    val basic = stringProvider.getString(R.string.basic)
    val show_mosque_name = stringProvider.getString(R.string.show_mosque_name)
    val time_format = stringProvider.getString(R.string.time_format)
    val twenty_four_hour_format = stringProvider.getString(R.string.twenty_four_hour_format)
    val default_prayer_times = stringProvider.getString(R.string.default_prayer_times)
    val fajr = stringProvider.getString(R.string.fajr)
    val dhuhr = stringProvider.getString(R.string.dhuhr)
    val asr = stringProvider.getString(R.string.asr)
    val maghrib = stringProvider.getString(R.string.maghrib)
    val isha = stringProvider.getString(R.string.isha)
    val jumah = stringProvider.getString(R.string.jumah)
    val sunrise = stringProvider.getString(R.string.sunrise)
    val background_image = stringProvider.getString(R.string.background_image)
    val current_background = stringProvider.getString(R.string.current_background)
    val default_background = stringProvider.getString(R.string.default_background)
    val change_background_image = stringProvider.getString(R.string.change_background_image)
    val notifications = stringProvider.getString(R.string.notifications)
    val pre_prayer_notifications = stringProvider.getString(R.string.pre_prayer_notifications)
    val post_prayer_notifications = stringProvider.getString(R.string.post_prayer_notifications)
    val account_and_sync = stringProvider.getString(R.string.account_and_sync)
    val logged_in_as = stringProvider.getString(R.string.logged_in_as)
    val sync_data = stringProvider.getString(R.string.sync_data)
    val logout = stringProvider.getString(R.string.logout)
    val not_logged_in = stringProvider.getString(R.string.not_logged_in)
    val login_to_sync_data = stringProvider.getString(R.string.login_to_sync_data)
    val back_to_main_screen = stringProvider.getString(R.string.back_to_main_screen)
    val set_prayer_time = stringProvider.getString(R.string.set_prayer_time)
    val select_time = stringProvider.getString(R.string.select_time)
    val hour = stringProvider.getString(R.string.hour)
    val minute = stringProvider.getString(R.string.minute)
    val ok = stringProvider.getString(R.string.ok)
    val cancel = stringProvider.getString(R.string.cancel)
    val select_background_image = stringProvider.getString(R.string.select_background_image)
    val choose_background_image = stringProvider.getString(R.string.choose_background_image)
    val selected_image = stringProvider.getString(R.string.selected_image)
    val select = stringProvider.getString(R.string.select)
    val add_image_url = stringProvider.getString(R.string.add_image_url)
    val url = stringProvider.getString(R.string.url)
    val add = stringProvider.getString(R.string.add)
    val select_image = stringProvider.getString(R.string.select_image)
    val no_image_picker_available = stringProvider.getString(R.string.no_image_picker_available)
    val welcome_to_app = stringProvider.getString(R.string.welcome_to_app)
    val permission_prompt = stringProvider.getString(R.string.permission_prompt)
    val media_audio_access = stringProvider.getString(R.string.media_audio_access)
    val media_audio_access_description = stringProvider.getString(R.string.media_audio_access_description)
    val post_notifications = stringProvider.getString(R.string.post_notifications)
    val post_notifications_description = stringProvider.getString(R.string.post_notifications_description)
    val storage_access = stringProvider.getString(R.string.storage_access)
    val storage_access_description = stringProvider.getString(R.string.storage_access_description)
    val nearby_devices = stringProvider.getString(R.string.nearby_devices)
    val nearby_devices_description = stringProvider.getString(R.string.nearby_devices_description)
    val alarms_and_reminders = stringProvider.getString(R.string.alarms_and_reminders)

}